# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.accounts_get import AccountsGet  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountsGet(unittest.TestCase):
    """AccountsGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountsGet(self):
        """Test AccountsGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.accounts_get.AccountsGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
