# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.journals_api import JournalsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestJournalsApi(unittest.TestCase):
    """JournalsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.journals_api.JournalsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_journals_list(self):
        """Test case for journals_list

        List Journal Entries for this accountname  # noqa: E501
        """
        pass

    def test_journals_post(self):
        """Test case for journals_post

        Create a journal entry for this account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
