# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.delete_response import DeleteResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestDeleteResponse(unittest.TestCase):
    """DeleteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteResponse(self):
        """Test DeleteResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.delete_response.DeleteResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
