# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.auth_api import AuthApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.auth_api.AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_get(self):
        """Test case for account_get

        Get Steward account information  # noqa: E501
        """
        pass

    def test_login_get(self):
        """Test case for login_get

        Login Page for the steward  # noqa: E501
        """
        pass

    def test_login_post(self):
        """Test case for login_post

        Login steward  # noqa: E501
        """
        pass

    def test_logout_post(self):
        """Test case for logout_post

        Logout steward  # noqa: E501
        """
        pass

    def test_oauth_access_token_post(self):
        """Test case for oauth_access_token_post

        Exchanges the user or client credentials for an access token used to access resources.  # noqa: E501
        """
        pass

    def test_oauth_application_post(self):
        """Test case for oauth_application_post

        Create an application for a client_id and client_secret for oauth token authorization.  # noqa: E501
        """
        pass

    def test_oauth_dialoge_get(self):
        """Test case for oauth_dialoge_get

        Implicit authorization dialog presented to steward to authorize client_id to access API resources on their behalf.  # noqa: E501
        """
        pass

    def test_oauth_dialoge_post(self):
        """Test case for oauth_dialoge_post

        Authorizes a steward on the openmoney network  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
