# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.namespaces_api import NamespacesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNamespacesApi(unittest.TestCase):
    """NamespacesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.namespaces_api.NamespacesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_spaces_delete(self):
        """Test case for spaces_delete

        """
        pass

    def test_spaces_get(self):
        """Test case for spaces_get

        Get a namespace by it's name  # noqa: E501
        """
        pass

    def test_spaces_list(self):
        """Test case for spaces_list

        Get a Listing of namespaces known by steward.  # noqa: E501
        """
        pass

    def test_spaces_post(self):
        """Test case for spaces_post

        Create a namespace  # noqa: E501
        """
        pass

    def test_spaces_put(self):
        """Test case for spaces_put

        Update a namespace  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
