# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accounts_api import AccountsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.accounts_api.AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accounts_delete(self):
        """Test case for accounts_delete

        Delete an account  # noqa: E501
        """
        pass

    def test_accounts_discovery(self):
        """Test case for accounts_discovery

        Lookup an account by it's public key  # noqa: E501
        """
        pass

    def test_accounts_get(self):
        """Test case for accounts_get

        Get an account by account name  # noqa: E501
        """
        pass

    def test_accounts_list(self):
        """Test case for accounts_list

        Get a Listing of accounts in a namespace  # noqa: E501
        """
        pass

    def test_accounts_post(self):
        """Test case for accounts_post

        create an account in a namespace  # noqa: E501
        """
        pass

    def test_accounts_put(self):
        """Test case for accounts_put

        Update an account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
