# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.aes_encryption import AesEncryption  # noqa: E501
from swagger_client.rest import ApiException


class TestAesEncryption(unittest.TestCase):
    """AesEncryption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAesEncryption(self):
        """Test AesEncryption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.aes_encryption.AesEncryption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
