# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.stewards_api import StewardsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStewardsApi(unittest.TestCase):
    """StewardsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.stewards_api.StewardsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_stewards_delete(self):
        """Test case for stewards_delete

        Delete a steward account  # noqa: E501
        """
        pass

    def test_stewards_forgot_post(self):
        """Test case for stewards_forgot_post

        Forgot password or stewardname request  # noqa: E501
        """
        pass

    def test_stewards_get(self):
        """Test case for stewards_get

        Get a single steward  # noqa: E501
        """
        pass

    def test_stewards_list(self):
        """Test case for stewards_list

        Get a listing of known stewards  # noqa: E501
        """
        pass

    def test_stewards_post(self):
        """Test case for stewards_post

        Register a steward on the system  # noqa: E501
        """
        pass

    def test_stewards_put(self):
        """Test case for stewards_put

        Update a steward account  # noqa: E501
        """
        pass

    def test_stewards_reset_post(self):
        """Test case for stewards_reset_post

        Reset password request  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
