# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AccessTokenRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'grant_type': 'str',
        'client_id': 'str',
        'client_secret': 'str',
        'username': 'str',
        'password': 'str',
        'refresh_token': 'str'
    }

    attribute_map = {
        'grant_type': 'grant_type',
        'client_id': 'client_id',
        'client_secret': 'client_secret',
        'username': 'username',
        'password': 'password',
        'refresh_token': 'refresh_token'
    }

    def __init__(self, grant_type=None, client_id=None, client_secret=None, username=None, password=None, refresh_token=None):  # noqa: E501
        """AccessTokenRequest - a model defined in Swagger"""  # noqa: E501

        self._grant_type = None
        self._client_id = None
        self._client_secret = None
        self._username = None
        self._password = None
        self._refresh_token = None
        self.discriminator = None

        self.grant_type = grant_type
        if client_id is not None:
            self.client_id = client_id
        if client_secret is not None:
            self.client_secret = client_secret
        if username is not None:
            self.username = username
        if password is not None:
            self.password = password
        if refresh_token is not None:
            self.refresh_token = refresh_token

    @property
    def grant_type(self):
        """Gets the grant_type of this AccessTokenRequest.  # noqa: E501

        one of code, password, refresh_token, client_credentials  # noqa: E501

        :return: The grant_type of this AccessTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._grant_type

    @grant_type.setter
    def grant_type(self, grant_type):
        """Sets the grant_type of this AccessTokenRequest.

        one of code, password, refresh_token, client_credentials  # noqa: E501

        :param grant_type: The grant_type of this AccessTokenRequest.  # noqa: E501
        :type: str
        """
        if grant_type is None:
            raise ValueError("Invalid value for `grant_type`, must not be `None`")  # noqa: E501
        if grant_type is not None and len(grant_type) > 20:
            raise ValueError("Invalid value for `grant_type`, length must be less than or equal to `20`")  # noqa: E501
        if grant_type is not None and not re.search(r'^[A-Za-z_]+$', grant_type):  # noqa: E501
            raise ValueError(r"Invalid value for `grant_type`, must be a follow pattern or equal to `/^[A-Za-z_]+$/`")  # noqa: E501

        self._grant_type = grant_type

    @property
    def client_id(self):
        """Gets the client_id of this AccessTokenRequest.  # noqa: E501

        Stewards Public Key  # noqa: E501

        :return: The client_id of this AccessTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this AccessTokenRequest.

        Stewards Public Key  # noqa: E501

        :param client_id: The client_id of this AccessTokenRequest.  # noqa: E501
        :type: str
        """
        if client_id is not None and len(client_id) > 800:
            raise ValueError("Invalid value for `client_id`, length must be less than or equal to `800`")  # noqa: E501
        if client_id is not None and len(client_id) < 5:
            raise ValueError("Invalid value for `client_id`, length must be greater than or equal to `5`")  # noqa: E501
        if client_id is not None and not re.search(r'^[A-Za-z0-9\\\\\\s\/=+-]*$', client_id):  # noqa: E501
            raise ValueError(r"Invalid value for `client_id`, must be a follow pattern or equal to `/^[A-Za-z0-9\\\\\\s\/=+-]*$/`")  # noqa: E501

        self._client_id = client_id

    @property
    def client_secret(self):
        """Gets the client_secret of this AccessTokenRequest.  # noqa: E501

        Client Secret  # noqa: E501

        :return: The client_secret of this AccessTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_secret

    @client_secret.setter
    def client_secret(self, client_secret):
        """Sets the client_secret of this AccessTokenRequest.

        Client Secret  # noqa: E501

        :param client_secret: The client_secret of this AccessTokenRequest.  # noqa: E501
        :type: str
        """
        if client_secret is not None and len(client_secret) > 1600:
            raise ValueError("Invalid value for `client_secret`, length must be less than or equal to `1600`")  # noqa: E501
        if client_secret is not None and len(client_secret) < 32:
            raise ValueError("Invalid value for `client_secret`, length must be greater than or equal to `32`")  # noqa: E501
        if client_secret is not None and not re.search(r'^[A-Za-z0-9\\\\\\\\\\\\s\/=+-]*$', client_secret):  # noqa: E501
            raise ValueError(r"Invalid value for `client_secret`, must be a follow pattern or equal to `/^[A-Za-z0-9\\\\\\\\\\\\s\/=+-]*$/`")  # noqa: E501

        self._client_secret = client_secret

    @property
    def username(self):
        """Gets the username of this AccessTokenRequest.  # noqa: E501


        :return: The username of this AccessTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this AccessTokenRequest.


        :param username: The username of this AccessTokenRequest.  # noqa: E501
        :type: str
        """
        if username is not None and not re.search(r'^[A-Za-z0-9_.-]+$', username):  # noqa: E501
            raise ValueError(r"Invalid value for `username`, must be a follow pattern or equal to `/^[A-Za-z0-9_.-]+$/`")  # noqa: E501

        self._username = username

    @property
    def password(self):
        """Gets the password of this AccessTokenRequest.  # noqa: E501


        :return: The password of this AccessTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this AccessTokenRequest.


        :param password: The password of this AccessTokenRequest.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def refresh_token(self):
        """Gets the refresh_token of this AccessTokenRequest.  # noqa: E501


        :return: The refresh_token of this AccessTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token):
        """Sets the refresh_token of this AccessTokenRequest.


        :param refresh_token: The refresh_token of this AccessTokenRequest.  # noqa: E501
        :type: str
        """

        self._refresh_token = refresh_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccessTokenRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccessTokenRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
