# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApplicationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'application_id': 'str',
        'application_secret': 'str'
    }

    attribute_map = {
        'application_id': 'application_id',
        'application_secret': 'application_secret'
    }

    def __init__(self, application_id=None, application_secret=None):  # noqa: E501
        """ApplicationResponse - a model defined in Swagger"""  # noqa: E501

        self._application_id = None
        self._application_secret = None
        self.discriminator = None

        self.application_id = application_id
        self.application_secret = application_secret

    @property
    def application_id(self):
        """Gets the application_id of this ApplicationResponse.  # noqa: E501


        :return: The application_id of this ApplicationResponse.  # noqa: E501
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this ApplicationResponse.


        :param application_id: The application_id of this ApplicationResponse.  # noqa: E501
        :type: str
        """
        if application_id is None:
            raise ValueError("Invalid value for `application_id`, must not be `None`")  # noqa: E501
        if application_id is not None and len(application_id) > 800:
            raise ValueError("Invalid value for `application_id`, length must be less than or equal to `800`")  # noqa: E501
        if application_id is not None and len(application_id) < 266:
            raise ValueError("Invalid value for `application_id`, length must be greater than or equal to `266`")  # noqa: E501
        if application_id is not None and not re.search(r'^-----BEGIN PUBLIC KEY-----[A-Za-z0-9\\\\\\s\/=+]+-----END PUBLIC KEY-----$', application_id):  # noqa: E501
            raise ValueError(r"Invalid value for `application_id`, must be a follow pattern or equal to `/^-----BEGIN PUBLIC KEY-----[A-Za-z0-9\\\\\\s\/=+]+-----END PUBLIC KEY-----$/`")  # noqa: E501

        self._application_id = application_id

    @property
    def application_secret(self):
        """Gets the application_secret of this ApplicationResponse.  # noqa: E501


        :return: The application_secret of this ApplicationResponse.  # noqa: E501
        :rtype: str
        """
        return self._application_secret

    @application_secret.setter
    def application_secret(self, application_secret):
        """Sets the application_secret of this ApplicationResponse.


        :param application_secret: The application_secret of this ApplicationResponse.  # noqa: E501
        :type: str
        """
        if application_secret is None:
            raise ValueError("Invalid value for `application_secret`, must not be `None`")  # noqa: E501
        if application_secret is not None and len(application_secret) > 899:
            raise ValueError("Invalid value for `application_secret`, length must be less than or equal to `899`")  # noqa: E501
        if application_secret is not None and len(application_secret) < 893:
            raise ValueError("Invalid value for `application_secret`, length must be greater than or equal to `893`")  # noqa: E501
        if application_secret is not None and not re.search(r'^-----BEGIN PRIVATE KEY-----[A-Za-z0-9\/+]{845,848}[=]{0,3}-----END PRIVATE KEY-----$', application_secret):  # noqa: E501
            raise ValueError(r"Invalid value for `application_secret`, must be a follow pattern or equal to `/^-----BEGIN PRIVATE KEY-----[A-Za-z0-9\/+]{845,848}[=]{0,3}-----END PRIVATE KEY-----$/`")  # noqa: E501

        self._application_secret = application_secret

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApplicationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApplicationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
