# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EncryptedJournals(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'type': 'str',
        'algorithm': 'str',
        'public_key_encrypted_symetric_key': 'str',
        'initialization_vector': 'str',
        'encrypted_journal': 'AesEncryption'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'algorithm': 'algorithm',
        'public_key_encrypted_symetric_key': 'publicKeyEncryptedSymetricKey',
        'initialization_vector': 'initializationVector',
        'encrypted_journal': 'encryptedJournal'
    }

    def __init__(self, id=None, type=None, algorithm=None, public_key_encrypted_symetric_key=None, initialization_vector=None, encrypted_journal=None):  # noqa: E501
        """EncryptedJournals - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._type = None
        self._algorithm = None
        self._public_key_encrypted_symetric_key = None
        self._initialization_vector = None
        self._encrypted_journal = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if algorithm is not None:
            self.algorithm = algorithm
        if public_key_encrypted_symetric_key is not None:
            self.public_key_encrypted_symetric_key = public_key_encrypted_symetric_key
        if initialization_vector is not None:
            self.initialization_vector = initialization_vector
        if encrypted_journal is not None:
            self.encrypted_journal = encrypted_journal

    @property
    def id(self):
        """Gets the id of this EncryptedJournals.  # noqa: E501


        :return: The id of this EncryptedJournals.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EncryptedJournals.


        :param id: The id of this EncryptedJournals.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this EncryptedJournals.  # noqa: E501


        :return: The type of this EncryptedJournals.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this EncryptedJournals.


        :param type: The type of this EncryptedJournals.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def algorithm(self):
        """Gets the algorithm of this EncryptedJournals.  # noqa: E501


        :return: The algorithm of this EncryptedJournals.  # noqa: E501
        :rtype: str
        """
        return self._algorithm

    @algorithm.setter
    def algorithm(self, algorithm):
        """Sets the algorithm of this EncryptedJournals.


        :param algorithm: The algorithm of this EncryptedJournals.  # noqa: E501
        :type: str
        """

        self._algorithm = algorithm

    @property
    def public_key_encrypted_symetric_key(self):
        """Gets the public_key_encrypted_symetric_key of this EncryptedJournals.  # noqa: E501


        :return: The public_key_encrypted_symetric_key of this EncryptedJournals.  # noqa: E501
        :rtype: str
        """
        return self._public_key_encrypted_symetric_key

    @public_key_encrypted_symetric_key.setter
    def public_key_encrypted_symetric_key(self, public_key_encrypted_symetric_key):
        """Sets the public_key_encrypted_symetric_key of this EncryptedJournals.


        :param public_key_encrypted_symetric_key: The public_key_encrypted_symetric_key of this EncryptedJournals.  # noqa: E501
        :type: str
        """

        self._public_key_encrypted_symetric_key = public_key_encrypted_symetric_key

    @property
    def initialization_vector(self):
        """Gets the initialization_vector of this EncryptedJournals.  # noqa: E501


        :return: The initialization_vector of this EncryptedJournals.  # noqa: E501
        :rtype: str
        """
        return self._initialization_vector

    @initialization_vector.setter
    def initialization_vector(self, initialization_vector):
        """Sets the initialization_vector of this EncryptedJournals.


        :param initialization_vector: The initialization_vector of this EncryptedJournals.  # noqa: E501
        :type: str
        """

        self._initialization_vector = initialization_vector

    @property
    def encrypted_journal(self):
        """Gets the encrypted_journal of this EncryptedJournals.  # noqa: E501


        :return: The encrypted_journal of this EncryptedJournals.  # noqa: E501
        :rtype: AesEncryption
        """
        return self._encrypted_journal

    @encrypted_journal.setter
    def encrypted_journal(self, encrypted_journal):
        """Sets the encrypted_journal of this EncryptedJournals.


        :param encrypted_journal: The encrypted_journal of this EncryptedJournals.  # noqa: E501
        :type: AesEncryption
        """

        self._encrypted_journal = encrypted_journal

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EncryptedJournals, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EncryptedJournals):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
