# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ForgotRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stewardname': 'str',
        'email': 'str'
    }

    attribute_map = {
        'stewardname': 'stewardname',
        'email': 'email'
    }

    def __init__(self, stewardname=None, email=None):  # noqa: E501
        """ForgotRequest - a model defined in Swagger"""  # noqa: E501

        self._stewardname = None
        self._email = None
        self.discriminator = None

        if stewardname is not None:
            self.stewardname = stewardname
        if email is not None:
            self.email = email

    @property
    def stewardname(self):
        """Gets the stewardname of this ForgotRequest.  # noqa: E501


        :return: The stewardname of this ForgotRequest.  # noqa: E501
        :rtype: str
        """
        return self._stewardname

    @stewardname.setter
    def stewardname(self, stewardname):
        """Sets the stewardname of this ForgotRequest.


        :param stewardname: The stewardname of this ForgotRequest.  # noqa: E501
        :type: str
        """
        if stewardname is not None and len(stewardname) > 255:
            raise ValueError("Invalid value for `stewardname`, length must be less than or equal to `255`")  # noqa: E501
        if stewardname is not None and not re.search(r'^[A-Za-z0-9_.-]+$', stewardname):  # noqa: E501
            raise ValueError(r"Invalid value for `stewardname`, must be a follow pattern or equal to `/^[A-Za-z0-9_.-]+$/`")  # noqa: E501

        self._stewardname = stewardname

    @property
    def email(self):
        """Gets the email of this ForgotRequest.  # noqa: E501


        :return: The email of this ForgotRequest.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this ForgotRequest.


        :param email: The email of this ForgotRequest.  # noqa: E501
        :type: str
        """
        if email is not None and len(email) > 255:
            raise ValueError("Invalid value for `email`, length must be less than or equal to `255`")  # noqa: E501
        if email is not None and not re.search(r'^([\\w-]+(?:[\\.\\+][\\w-]+)*)@((?:[\\w-]+\\.)*\\w[\\w-]{0,66})\\.([a-z]{2,6}(?:\\.[a-z]{2})?)$', email):  # noqa: E501
            raise ValueError(r"Invalid value for `email`, must be a follow pattern or equal to `/^([\\w-]+(?:[\\.\\+][\\w-]+)*)@((?:[\\w-]+\\.)*\\w[\\w-]{0,66})\\.([a-z]{2,6}(?:\\.[a-z]{2})?)$/`")  # noqa: E501

        self._email = email

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ForgotRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ForgotRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
