# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class JournalsRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'to_account': 'str',
        'to_account_namespace': 'str',
        'amount': 'float',
        'payload': 'object'
    }

    attribute_map = {
        'to_account': 'to_account',
        'to_account_namespace': 'to_account_namespace',
        'amount': 'amount',
        'payload': 'payload'
    }

    def __init__(self, to_account=None, to_account_namespace=None, amount=None, payload=None):  # noqa: E501
        """JournalsRequest - a model defined in Swagger"""  # noqa: E501

        self._to_account = None
        self._to_account_namespace = None
        self._amount = None
        self._payload = None
        self.discriminator = None

        self.to_account = to_account
        self.to_account_namespace = to_account_namespace
        self.amount = amount
        if payload is not None:
            self.payload = payload

    @property
    def to_account(self):
        """Gets the to_account of this JournalsRequest.  # noqa: E501


        :return: The to_account of this JournalsRequest.  # noqa: E501
        :rtype: str
        """
        return self._to_account

    @to_account.setter
    def to_account(self, to_account):
        """Sets the to_account of this JournalsRequest.


        :param to_account: The to_account of this JournalsRequest.  # noqa: E501
        :type: str
        """
        if to_account is None:
            raise ValueError("Invalid value for `to_account`, must not be `None`")  # noqa: E501
        if to_account is not None and len(to_account) > 255:
            raise ValueError("Invalid value for `to_account`, length must be less than or equal to `255`")  # noqa: E501
        if to_account is not None and not re.search(r'^[A-Za-z0-9_-]+$', to_account):  # noqa: E501
            raise ValueError(r"Invalid value for `to_account`, must be a follow pattern or equal to `/^[A-Za-z0-9_-]+$/`")  # noqa: E501

        self._to_account = to_account

    @property
    def to_account_namespace(self):
        """Gets the to_account_namespace of this JournalsRequest.  # noqa: E501


        :return: The to_account_namespace of this JournalsRequest.  # noqa: E501
        :rtype: str
        """
        return self._to_account_namespace

    @to_account_namespace.setter
    def to_account_namespace(self, to_account_namespace):
        """Sets the to_account_namespace of this JournalsRequest.


        :param to_account_namespace: The to_account_namespace of this JournalsRequest.  # noqa: E501
        :type: str
        """
        if to_account_namespace is None:
            raise ValueError("Invalid value for `to_account_namespace`, must not be `None`")  # noqa: E501
        if to_account_namespace is not None and len(to_account_namespace) > 255:
            raise ValueError("Invalid value for `to_account_namespace`, length must be less than or equal to `255`")  # noqa: E501
        if to_account_namespace is not None and not re.search(r'^[A-Za-z0-9_.-]+$', to_account_namespace):  # noqa: E501
            raise ValueError(r"Invalid value for `to_account_namespace`, must be a follow pattern or equal to `/^[A-Za-z0-9_.-]+$/`")  # noqa: E501

        self._to_account_namespace = to_account_namespace

    @property
    def amount(self):
        """Gets the amount of this JournalsRequest.  # noqa: E501


        :return: The amount of this JournalsRequest.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this JournalsRequest.


        :param amount: The amount of this JournalsRequest.  # noqa: E501
        :type: float
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501
        if amount is not None and amount < 0:  # noqa: E501
            raise ValueError("Invalid value for `amount`, must be a value greater than or equal to `0`")  # noqa: E501

        self._amount = amount

    @property
    def payload(self):
        """Gets the payload of this JournalsRequest.  # noqa: E501


        :return: The payload of this JournalsRequest.  # noqa: E501
        :rtype: object
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this JournalsRequest.


        :param payload: The payload of this JournalsRequest.  # noqa: E501
        :type: object
        """

        self._payload = payload

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JournalsRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JournalsRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
