# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Modification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'modified': 'int',
        'modified_by': 'str',
        'modification': 'str'
    }

    attribute_map = {
        'modified': 'modified',
        'modified_by': 'modified_by',
        'modification': 'modification'
    }

    def __init__(self, modified=None, modified_by=None, modification=None):  # noqa: E501
        """Modification - a model defined in Swagger"""  # noqa: E501

        self._modified = None
        self._modified_by = None
        self._modification = None
        self.discriminator = None

        if modified is not None:
            self.modified = modified
        if modified_by is not None:
            self.modified_by = modified_by
        if modification is not None:
            self.modification = modification

    @property
    def modified(self):
        """Gets the modified of this Modification.  # noqa: E501

        timestamp in milliseconds since epoch  # noqa: E501

        :return: The modified of this Modification.  # noqa: E501
        :rtype: int
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this Modification.

        timestamp in milliseconds since epoch  # noqa: E501

        :param modified: The modified of this Modification.  # noqa: E501
        :type: int
        """

        self._modified = modified

    @property
    def modified_by(self):
        """Gets the modified_by of this Modification.  # noqa: E501

        stewardname of steward who made modification  # noqa: E501

        :return: The modified_by of this Modification.  # noqa: E501
        :rtype: str
        """
        return self._modified_by

    @modified_by.setter
    def modified_by(self, modified_by):
        """Sets the modified_by of this Modification.

        stewardname of steward who made modification  # noqa: E501

        :param modified_by: The modified_by of this Modification.  # noqa: E501
        :type: str
        """

        self._modified_by = modified_by

    @property
    def modification(self):
        """Gets the modification of this Modification.  # noqa: E501

        human readable description of modification  # noqa: E501

        :return: The modification of this Modification.  # noqa: E501
        :rtype: str
        """
        return self._modification

    @modification.setter
    def modification(self, modification):
        """Sets the modification of this Modification.

        human readable description of modification  # noqa: E501

        :param modification: The modification of this Modification.  # noqa: E501
        :type: str
        """

        self._modification = modification

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Modification, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Modification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
