# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RegisterResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ok': 'bool',
        'stewards': 'list[StewardsResponse]'
    }

    attribute_map = {
        'ok': 'ok',
        'stewards': 'stewards'
    }

    def __init__(self, ok=None, stewards=None):  # noqa: E501
        """RegisterResponse - a model defined in Swagger"""  # noqa: E501

        self._ok = None
        self._stewards = None
        self.discriminator = None

        if ok is not None:
            self.ok = ok
        if stewards is not None:
            self.stewards = stewards

    @property
    def ok(self):
        """Gets the ok of this RegisterResponse.  # noqa: E501


        :return: The ok of this RegisterResponse.  # noqa: E501
        :rtype: bool
        """
        return self._ok

    @ok.setter
    def ok(self, ok):
        """Sets the ok of this RegisterResponse.


        :param ok: The ok of this RegisterResponse.  # noqa: E501
        :type: bool
        """

        self._ok = ok

    @property
    def stewards(self):
        """Gets the stewards of this RegisterResponse.  # noqa: E501


        :return: The stewards of this RegisterResponse.  # noqa: E501
        :rtype: list[StewardsResponse]
        """
        return self._stewards

    @stewards.setter
    def stewards(self, stewards):
        """Sets the stewards of this RegisterResponse.


        :param stewards: The stewards of this RegisterResponse.  # noqa: E501
        :type: list[StewardsResponse]
        """

        self._stewards = stewards

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RegisterResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegisterResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
