# coding: utf-8

"""
    Openmoney API

    Openmoney API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ResetRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'forgot_token': 'str',
        'password': 'str'
    }

    attribute_map = {
        'forgot_token': 'forgot_token',
        'password': 'password'
    }

    def __init__(self, forgot_token=None, password=None):  # noqa: E501
        """ResetRequest - a model defined in Swagger"""  # noqa: E501

        self._forgot_token = None
        self._password = None
        self.discriminator = None

        if forgot_token is not None:
            self.forgot_token = forgot_token
        if password is not None:
            self.password = password

    @property
    def forgot_token(self):
        """Gets the forgot_token of this ResetRequest.  # noqa: E501


        :return: The forgot_token of this ResetRequest.  # noqa: E501
        :rtype: str
        """
        return self._forgot_token

    @forgot_token.setter
    def forgot_token(self, forgot_token):
        """Sets the forgot_token of this ResetRequest.


        :param forgot_token: The forgot_token of this ResetRequest.  # noqa: E501
        :type: str
        """

        self._forgot_token = forgot_token

    @property
    def password(self):
        """Gets the password of this ResetRequest.  # noqa: E501


        :return: The password of this ResetRequest.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this ResetRequest.


        :param password: The password of this ResetRequest.  # noqa: E501
        :type: str
        """
        if password is not None and len(password) > 1024:
            raise ValueError("Invalid value for `password`, length must be less than or equal to `1024`")  # noqa: E501
        if password is not None and len(password) < 4:
            raise ValueError("Invalid value for `password`, length must be greater than or equal to `4`")  # noqa: E501

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResetRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResetRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
